//! Stable domain identifiers.
//!
//! Every identifier is a newtype over an opaque 128-bit runtime ID so that a
//! `SessionId` can never be passed where a `CommitId` is expected. Runtime IDs
//! are generated by an [`IdGenerator`]; production uses random IDs, the testkit
//! uses a fixed sequence so golden tests stay reproducible.
//!
//! Identifiers serialize as 32 lowercase hex characters. This namespace is
//! independent from any database row ID or provider-issued ID.

use std::fmt;
use std::str::FromStr;

use serde::{Deserialize, Serialize};

/// Opaque 128-bit runtime identifier shared by all domain newtypes.
#[derive(Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct RuntimeId(u128);

impl RuntimeId {
    pub const fn from_u128(value: u128) -> Self {
        Self(value)
    }

    pub const fn as_u128(self) -> u128 {
        self.0
    }

    /// The all-zero ID is reserved as "unset" and is rejected by validation.
    pub const fn is_nil(self) -> bool {
        self.0 == 0
    }
}

impl fmt::Display for RuntimeId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{:032x}", self.0)
    }
}

impl fmt::Debug for RuntimeId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "RuntimeId({self})")
    }
}

/// Error returned when a textual ID cannot be parsed.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
#[error("invalid runtime id {input:?}: expected 32 lowercase hex characters")]
pub struct ParseIdError {
    pub input: String,
}

impl FromStr for RuntimeId {
    type Err = ParseIdError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let invalid = || ParseIdError {
            input: s.to_owned(),
        };
        if s.len() != 32
            || !s
                .bytes()
                .all(|b| b.is_ascii_digit() || (b'a'..=b'f').contains(&b))
        {
            return Err(invalid());
        }
        u128::from_str_radix(s, 16).map(Self).map_err(|_| invalid())
    }
}

impl Serialize for RuntimeId {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.collect_str(self)
    }
}

impl<'de> Deserialize<'de> for RuntimeId {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let text = String::deserialize(deserializer)?;
        text.parse().map_err(serde::de::Error::custom)
    }
}

/// Source of fresh runtime IDs. Implementations must never return the nil ID.
pub trait IdGenerator: Send + Sync {
    fn next_id(&self) -> RuntimeId;
}

/// Random 128-bit IDs for production runtimes.
#[derive(Debug, Default, Clone, Copy)]
pub struct RandomIdGenerator;

impl IdGenerator for RandomIdGenerator {
    fn next_id(&self) -> RuntimeId {
        loop {
            let id = RuntimeId(uuid::Uuid::new_v4().as_u128());
            if !id.is_nil() {
                return id;
            }
        }
    }
}

macro_rules! define_id {
    ($(#[$meta:meta])* $name:ident) => {
        $(#[$meta])*
        #[derive(Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
        #[serde(transparent)]
        pub struct $name(RuntimeId);

        impl $name {
            pub const fn from_runtime_id(id: RuntimeId) -> Self {
                Self(id)
            }

            pub const fn from_u128(value: u128) -> Self {
                Self(RuntimeId::from_u128(value))
            }

            pub const fn runtime_id(self) -> RuntimeId {
                self.0
            }

            pub const fn is_nil(self) -> bool {
                self.0.is_nil()
            }

            pub fn generate(generator: &dyn IdGenerator) -> Self {
                Self(generator.next_id())
            }
        }

        impl fmt::Display for $name {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                fmt::Display::fmt(&self.0, f)
            }
        }

        impl fmt::Debug for $name {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                write!(f, "{}({})", stringify!($name), self.0)
            }
        }

        impl FromStr for $name {
            type Err = ParseIdError;

            fn from_str(s: &str) -> Result<Self, Self::Err> {
                s.parse().map(Self)
            }
        }
    };
}

define_id!(
    /// One auditable individual. Never reissued for the same lineage.
    IndividualId
);
define_id!(
    /// One canonical commit in an individual's lineage.
    CommitId
);
define_id!(
    /// A runtime node (body/host) authorized to run the individual.
    NodeId
);
define_id!(
    /// One process lifetime of a runtime node.
    BootId
);
define_id!(SessionId);
define_id!(TurnId);
define_id!(CognitiveEpisodeId);
define_id!(EvidenceId);
define_id!(ProposalId);
define_id!(ReceiptId);
define_id!(MemoryId);
define_id!(LibraryArtifactId);
define_id!(LibraryChunkId);
define_id!(
    /// One Persona Core backend. Deliberately a different type from
    /// [`ResourceId`]: a Persona backend is what speaks as the individual, a
    /// resource is something the individual delegates a subtask to, and the
    /// type system is where that distinction should be impossible to lose.
    PersonaBackendId
);
define_id!(
    /// One operator-authored persona seed. Distinct from
    /// [`PersonaBackendId`]: the seed is the disposition an operator
    /// configured, the backend is whatever currently runs it, and either can
    /// be replaced without the other.
    PersonaSeedId
);
define_id!(ResourceId);
define_id!(ResourceCallId);
define_id!(TraceId);
define_id!(AuditEventId);

/// Version of the mutation policy that evaluated a proposal.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(transparent)]
pub struct PolicyVersion(pub u32);

impl fmt::Display for PolicyVersion {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "policy-v{}", self.0)
    }
}

/// Version of the canonical storage schema.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(transparent)]
pub struct SchemaVersion(pub u32);

impl fmt::Display for SchemaVersion {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "schema-v{}", self.0)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn runtime_id_round_trips_through_hex() {
        let id = RuntimeId::from_u128(0x0123_4567_89ab_cdef_0011_2233_4455_6677);
        let text = id.to_string();
        assert_eq!(text.len(), 32);
        assert_eq!(text.parse::<RuntimeId>().unwrap(), id);
    }

    #[test]
    fn runtime_id_rejects_malformed_text() {
        assert!("".parse::<RuntimeId>().is_err());
        assert!("abc".parse::<RuntimeId>().is_err());
        assert!(
            "ZZ000000000000000000000000000000"
                .parse::<RuntimeId>()
                .is_err()
        );
        assert!(
            "0123456789ABCDEF0011223344556677"
                .parse::<RuntimeId>()
                .is_err()
        );
    }

    #[test]
    fn newtype_serializes_as_transparent_string() {
        let id = IndividualId::from_u128(7);
        let json = serde_json::to_string(&id).unwrap();
        assert_eq!(json, "\"00000000000000000000000000000007\"");
        let back: IndividualId = serde_json::from_str(&json).unwrap();
        assert_eq!(back, id);
    }

    #[test]
    fn random_generator_never_returns_nil() {
        let generator = RandomIdGenerator;
        for _ in 0..64 {
            assert!(!generator.next_id().is_nil());
        }
    }
}
