//! Deterministic ID generation for reproducible golden tests.

use std::sync::atomic::{AtomicU64, Ordering};

use kamimusuhi_core::ids::{Id128, IdGenerator};

/// Produces a strictly increasing sequence of IDs starting from a caller
/// chosen seed. Two `SequentialIdGenerator`s constructed with the same
/// seed and used in the same call order produce identical IDs, which is
/// what makes fixtures reproducible across test runs.
pub struct SequentialIdGenerator {
    next: AtomicU64,
    high_bits: u64,
}

impl SequentialIdGenerator {
    /// `namespace` occupies the high 64 bits so IDs generated by
    /// different fixtures/domains never collide even at low sequence
    /// numbers, while still being fully deterministic.
    pub fn new(namespace: u64) -> Self {
        SequentialIdGenerator {
            next: AtomicU64::new(1),
            high_bits: namespace,
        }
    }
}

impl Default for SequentialIdGenerator {
    fn default() -> Self {
        Self::new(0)
    }
}

impl IdGenerator for SequentialIdGenerator {
    fn next_id(&self) -> Id128 {
        let low = self.next.fetch_add(1, Ordering::SeqCst);
        Id128::from_u128(((self.high_bits as u128) << 64) | low as u128)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sequential_generator_is_deterministic_and_ordered() {
        let gen_a = SequentialIdGenerator::new(42);
        let gen_b = SequentialIdGenerator::new(42);
        assert_eq!(gen_a.next_id(), gen_b.next_id());
        let first = gen_a.next_id();
        let second = gen_a.next_id();
        assert!(second.as_u128() > first.as_u128());
    }
}
