-- Migration 0001: canonical / continuity tables (plan §6.1).
--
-- Do not edit this file once it has shipped in any committed history.
-- Future schema changes are new migration files, applied on top.

CREATE TABLE individuals (
    individual_id TEXT PRIMARY KEY,
    created_at TEXT NOT NULL,
    root_commit_id TEXT NOT NULL
);

CREATE TABLE canonical_commits (
    commit_id TEXT PRIMARY KEY,
    individual_id TEXT NOT NULL REFERENCES individuals (individual_id),
    generation INTEGER NOT NULL,
    predecessor_commit_id TEXT REFERENCES canonical_commits (commit_id),
    proposal_id TEXT,
    created_at TEXT NOT NULL,
    UNIQUE (individual_id, generation)
);

CREATE TABLE continuity_heads (
    individual_id TEXT PRIMARY KEY REFERENCES individuals (individual_id),
    commit_id TEXT NOT NULL REFERENCES canonical_commits (commit_id),
    generation INTEGER NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE mutation_proposals (
    proposal_id TEXT PRIMARY KEY,
    individual_id TEXT NOT NULL REFERENCES individuals (individual_id),
    domain TEXT NOT NULL,
    operation TEXT NOT NULL,
    candidate_json TEXT NOT NULL,
    expected_commit_id TEXT,
    expected_generation INTEGER NOT NULL,
    origin_class TEXT NOT NULL,
    requested_by TEXT NOT NULL,
    policy_version INTEGER NOT NULL,
    idempotency_key TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL
);

CREATE TABLE mutation_decisions (
    proposal_id TEXT PRIMARY KEY REFERENCES mutation_proposals (proposal_id),
    disposition TEXT NOT NULL,
    reason_code TEXT NOT NULL,
    decided_at TEXT NOT NULL
);

CREATE TABLE activation_receipts (
    receipt_id TEXT PRIMARY KEY,
    proposal_id TEXT NOT NULL UNIQUE REFERENCES mutation_proposals (proposal_id),
    commit_id TEXT NOT NULL UNIQUE REFERENCES canonical_commits (commit_id),
    predecessor_commit_id TEXT,
    generation INTEGER NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE audit_events (
    audit_event_id INTEGER PRIMARY KEY AUTOINCREMENT,
    individual_id TEXT,
    kind TEXT NOT NULL,
    proposal_id TEXT,
    commit_id TEXT,
    detail_json TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE INDEX idx_canonical_commits_individual ON canonical_commits (individual_id);
CREATE INDEX idx_audit_events_individual ON audit_events (individual_id);
